import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";

const WASM_URL =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const GEMINI_MODEL = "gemini-omni-flash-preview";
const STYLES = {
  movie3d:
    "Transform the person into a 3D animated movie character (stylized CGI " +
    "animation look, expressive big eyes, soft lighting).",
  anime:
    "Redraw the video as a hand-drawn anime with clean line art, cel " +
    "shading, and vibrant colors.",
  clay: "Transform the scene into claymation stop-motion with visible clay texture.",
  watercolor:
    "Repaint the video as a soft watercolor painting with loose brushwork.",
};
const PROMPT_SUFFIX =
  " This is a strict pixel-aligned edit of the source video: keep the same " +
  "pose, motion, timing, clothing colors, and background. The camera must " +
  "not change — no zoom, no crop, no recentering, and no change to the " +
  "field of view. The person's face and body must stay at exactly the same " +
  "position and size in the frame as the source: eyes, nose, and mouth must " +
  "remain at the same screen coordinates in every frame. Match the facial " +
  "expression exactly, frame by frame: preserve the exact degree of mouth " +
  "openness at every moment — if the mouth is slightly open and still, keep " +
  "it slightly open and still; do not close it, and do not add talking or " +
  "any mouth movement that is not in the source. Mirror blinks, gaze " +
  "direction, and eyebrow position at the same moments as the source. " +
  "Change only the visual style, nothing about the geometry, composition, " +
  "or performance.";

const WRIST = 0, THUMB_TIP = 4, INDEX_TIP = 8, MIDDLE_MCP = 9;

// Tracking constants — same audited pipeline as the live web app.
const MAX_LOST_FRAMES = 25;
const JUMP_CONFIRM_FRAMES = 2;

const orig = document.getElementById("orig");
const sty = document.getElementById("sty");
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
const statusEl = document.getElementById("status");
const stage = document.getElementById("stage");
const drop = document.getElementById("drop");
const btnGenerate = document.getElementById("btn-generate");
const btnPlaceholder = document.getElementById("btn-placeholder");
const btnPlay = document.getElementById("btn-play");
const btnExport = document.getElementById("btn-export");

let landmarker = null;
let videoFile = null;
let haveAI = false;        // stylized video generated by Gemini
let usePlaceholder = false; // hue-shift stand-in for keyless testing
let corners = null;
let presence = 0;
let frameActive = false;
let lostFrames = 0;
let jumpFrames = 0;
let sampledFrames = 0; // video frames this pass advanced through
let trackedFrames = 0; // of those, frames the finger frame was visible on
let recorder = null;
let exporting = false;

function status(msg) {
  statusEl.textContent = msg;
  // Messages ending in an ellipsis are in-progress — show the spinner.
  statusEl.classList.toggle("working", /…\s*$/.test(msg));
}

// ---- key + style panel ----
const keyInput = document.getElementById("gem-key");
const keyRemember = document.getElementById("gem-remember");
const styleSelect = document.getElementById("style-select");
const styleCustom = document.getElementById("style-custom");

keyInput.value =
  localStorage.getItem("gemini-key") || sessionStorage.getItem("gemini-key") || "";
keyRemember.checked = !!localStorage.getItem("gemini-key");
styleSelect.value = localStorage.getItem("ai-style") || "movie3d";
styleCustom.value = localStorage.getItem("ai-style-custom") || "";
styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
styleSelect.addEventListener("change", () => {
  styleCustom.classList.toggle("hidden", styleSelect.value !== "custom");
  localStorage.setItem("ai-style", styleSelect.value);
});
styleCustom.addEventListener("change", () =>
  localStorage.setItem("ai-style-custom", styleCustom.value)
);
function saveKey() {
  const key = keyInput.value.trim();
  localStorage.removeItem("gemini-key");
  sessionStorage.removeItem("gemini-key");
  if (key) (keyRemember.checked ? localStorage : sessionStorage).setItem("gemini-key", key);
  return key;
}
function prompt() {
  const style =
    styleSelect.value === "custom" && styleCustom.value.trim()
      ? styleCustom.value.trim()
      : STYLES[styleSelect.value] || STYLES.movie3d;
  return style + PROMPT_SUFFIX;
}

// ---- video loading ----
document.getElementById("file").addEventListener("change", (e) => {
  if (e.target.files[0]) loadVideo(e.target.files[0]);
});
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("over");
});
drop.addEventListener("dragleave", () => drop.classList.remove("over"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("over");
  if (e.dataTransfer.files[0]) loadVideo(e.dataTransfer.files[0]);
});

async function loadVideo(file) {
  videoFile = file;
  haveAI = false;
  usePlaceholder = false;
  btnPlay.disabled = true;
  btnExport.disabled = true;
  orig.src = URL.createObjectURL(file);
  await new Promise((res) => (orig.onloadedmetadata = res));
  canvas.width = orig.videoWidth;
  canvas.height = orig.videoHeight;
  stage.style.display = "flex";
  drop.classList.add("compact");
  drawPoster();
  status(
    `Loaded ${file.name} (${orig.videoWidth}×${orig.videoHeight}, ` +
    `${orig.duration.toFixed(1)}s). Generate the AI video, or test with the placeholder.`
  );
  if (!landmarker) initLandmarker();
}

function drawPoster() {
  orig.currentTime = 0.01;
  orig.onseeked = () => {
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    orig.onseeked = null;
  };
}

async function initLandmarker() {
  status("Loading hand tracker…");
  const fileset = await FilesetResolver.forVisionTasks(WASM_URL);
  landmarker = await HandLandmarker.createFromOptions(fileset, {
    baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
    runningMode: "VIDEO",
    numHands: 2,
    minHandDetectionConfidence: 0.3,
    minHandPresenceConfidence: 0.3,
    minTrackingConfidence: 0.3,
  });
  status("Hand tracker ready.");
}

// Dev hook: render one frame at time t (seconds) without realtime playback —
// lets automated tests drive the pipeline in environments that suspend media.
window.__step = (t) =>
  new Promise((resolve) => {
    orig.onseeked = () => {
      orig.onseeked = null;
      ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
      const res = landmarker.detectForVideo(orig, performance.now());
      updateTracker(res.landmarks || []);
      if (corners && presence > 0.01) {
        drawWindow(corners);
        drawOutline(corners, t);
      }
      resolve({
        presence: +presence.toFixed(2),
        corners: corners
          ? corners.map((p) => [Math.round(p.x), Math.round(p.y)])
          : null,
      });
    };
    orig.currentTime = t;
  });

// Dev convenience: ?src=file.mov loads a local file from the dev server.
const srcParam = new URLSearchParams(location.search).get("src");
if (srcParam) {
  fetch(srcParam)
    .then((r) => r.blob())
    .then((b) => loadVideo(new File([b], srcParam, { type: "video/quicktime" })));
}

// ---- AI generation (Gemini Omni Flash video editing, BYOK) ----

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const fr = new FileReader();
    fr.onload = () => resolve(fr.result.split(",")[1]);
    fr.onerror = reject;
    fr.readAsDataURL(file);
  });
}

async function gemFetch(key, path, init = {}) {
  const res = await fetch(`${GEMINI_BASE}/${path}`, {
    ...init,
    headers: {
      "x-goog-api-key": key,
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers || {}),
    },
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      detail = (await res.json())?.error?.message || detail;
    } catch {}
    throw new Error(`${res.status}: ${detail.slice(0, 160)}`);
  }
  return res.json();
}

// The Interactions API is in preview; be liberal about where the output
// video and status live in the response. Verified live shape: the video is
// in steps[].content[] on the step with type "model_output".
function findOutputVideo(inter) {
  if (inter.output_video) return inter.output_video;
  if (inter.outputVideo) return inter.outputVideo;
  const lists = [inter.outputs, inter.output, inter.content].filter(Array.isArray);
  for (const step of inter.steps || []) {
    if (Array.isArray(step.content)) lists.push(step.content);
  }
  for (const list of lists) {
    const v = list.find(
      (o) => o?.type?.includes?.("video") || o?.video || o?.mime_type?.startsWith?.("video")
    );
    if (v) return v.video || v;
  }
  return null;
}

function isPending(inter) {
  const s = (inter.status || inter.state || "").toLowerCase();
  return ["pending", "in_progress", "processing", "running", "queued"].some((k) =>
    s.includes(k)
  );
}

btnGenerate.addEventListener("click", async () => {
  const key = saveKey();
  if (!key) {
    status("Add your Gemini key above first (or use the placeholder).");
    keyInput.focus();
    return;
  }
  if (!videoFile) return;
  if (videoFile.size > 15 * 1024 * 1024) {
    status("⚠️ Keep the video under ~15MB (a few seconds of 720p) for inline upload.");
    return;
  }
  btnGenerate.disabled = true;
  try {
    status("Encoding video…");
    const b64 = await fileToBase64(videoFile);

    status("Submitting to Gemini Omni Flash — this can take a few minutes…");
    let inter = await gemFetch(key, "interactions", {
      method: "POST",
      body: JSON.stringify({
        model: GEMINI_MODEL,
        input: [
          {
            type: "video",
            mime_type: videoFile.type || "video/mp4",
            data: b64,
          },
          { type: "text", text: prompt() },
        ],
      }),
    });
    console.log("interaction response:", inter);

    // Poll the interaction until it settles, if it reports as in-progress.
    const id = inter.id || inter.name;
    let waited = 0;
    while (isPending(inter) && waited < 600) {
      await sleep(5000);
      waited += 5;
      inter = await gemFetch(key, `interactions/${id}`);
      status(`Generating… (${waited}s, status: ${inter.status || inter.state || "working"})`);
    }

    const vid = findOutputVideo(inter);
    if (!vid) {
      console.error("full response:", inter);
      throw new Error("no video in response — see console for the raw payload");
    }

    let blob;
    if (vid.data) {
      const bytes = Uint8Array.from(atob(vid.data), (c) => c.charCodeAt(0));
      blob = new Blob([bytes], { type: vid.mime_type || "video/mp4" });
    } else {
      // uri delivery: wait for the file to become ACTIVE, then download.
      let uri = vid.uri || vid.file_uri || vid.url;
      if (!uri) throw new Error("no video data or uri in response");
      const fileName = uri.includes("/files/")
        ? "files/" + uri.split("/files/")[1].split(/[?#]/)[0]
        : uri;
      if (!/^https?:/.test(uri)) uri = `${GEMINI_BASE}/${fileName}:download?alt=media`;
      for (let i = 0; i < 60; i++) {
        const f = await gemFetch(key, fileName);
        if ((f.state || "").includes("ACTIVE")) break;
        status(`Waiting for the output file… (${(f.state || "processing").toLowerCase()})`);
        await sleep(5000);
      }
      status("Downloading result…");
      const res = await fetch(uri, { headers: { "x-goog-api-key": key } });
      if (!res.ok) throw new Error(`download failed: ${res.status}`);
      blob = await res.blob();
    }

    sty.src = URL.createObjectURL(blob);
    await new Promise((res) => (sty.onloadedmetadata = res));
    haveAI = true;
    usePlaceholder = false;
    btnPlay.disabled = false;
    btnExport.disabled = false;
    status("AI video ready — preview or export.");
  } catch (err) {
    console.error(err);
    status("⚠️ Generation failed: " + (err.message || err));
  } finally {
    btnGenerate.disabled = false;
  }
});

btnPlaceholder.addEventListener("click", () => {
  if (!videoFile) return;
  usePlaceholder = true;
  haveAI = false;
  btnPlay.disabled = false;
  btnExport.disabled = false;
  status("Placeholder style active (hue shift) — preview or export, no key needed.");
});

// ---- tracking (ported from finger-frame-effect main.js) ----
function toPixel(lm) {
  return { x: lm.x * canvas.width, y: lm.y * canvas.height };
}
function dist(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
function lerpPt(a, b, t) {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}
function polygonArea(pts) {
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i], q = pts[(i + 1) % pts.length];
    a += p.x * q.y - q.x * p.y;
  }
  return Math.abs(a / 2);
}

function computeQuad(hands) {
  if (hands.length !== 2) return null;
  const info = hands.map((lm) => ({
    index: toPixel(lm[INDEX_TIP]),
    thumb: toPixel(lm[THUMB_TIP]),
    wristX: toPixel(lm[WRIST]).x,
    scale: dist(toPixel(lm[WRIST]), toPixel(lm[MIDDLE_MCP])) + 1,
  }));
  const needed = frameActive ? 0.2 : 0.75;
  for (const hd of info) {
    if (dist(hd.thumb, hd.index) < hd.scale * needed) return null;
  }
  info.sort((a, b) => a.wristX - b.wristX);
  const [A, B] = info;
  const pts = [A.index, B.index, B.thumb, A.thumb];
  const cx = pts.reduce((s, p) => s + p.x, 0) / 4;
  const cy = pts.reduce((s, p) => s + p.y, 0) / 4;
  const hull = [...pts].sort(
    (a, b) => Math.atan2(a.y - cy, a.x - cx) - Math.atan2(b.y - cy, b.x - cx)
  );
  const minArea = frameActive ? 0.0005 : 0.005;
  if (polygonArea(hull) < canvas.width * canvas.height * minArea) return null;
  return pts;
}

function updateTracker(hands) {
  const target = computeQuad(hands);
  if (target) {
    if (!corners) {
      lostFrames = 0;
      frameActive = true;
      jumpFrames = 0;
      corners = target;
      presence = Math.min(1, presence + 0.12);
    } else {
      const moved = target.reduce((s, p, i) => s + dist(p, corners[i]), 0) / 4;
      if (moved > canvas.width * 0.3 && ++jumpFrames < JUMP_CONFIRM_FRAMES) {
        if (++lostFrames > MAX_LOST_FRAMES) presence = Math.max(0, presence - 0.05);
      } else {
        lostFrames = 0;
        frameActive = true;
        jumpFrames = 0;
        const alpha = Math.min(0.85, Math.max(0.35, moved / (canvas.width * 0.05)));
        corners = corners.map((c, i) => lerpPt(c, target[i], alpha));
        presence = Math.min(1, presence + 0.12);
      }
    }
  } else if (corners && ++lostFrames <= MAX_LOST_FRAMES) {
    presence = Math.min(1, presence + 0.12);
  } else {
    presence = Math.max(0, presence - 0.05);
    if (presence === 0) {
      corners = null;
      frameActive = false;
      jumpFrames = 0;
    }
  }
}

// ---- rendering ----
function quadPath(q) {
  ctx.beginPath();
  ctx.moveTo(q[0].x, q[0].y);
  for (let i = 1; i < 4; i++) ctx.lineTo(q[i].x, q[i].y);
  ctx.closePath();
}

function drawWindow(q) {
  ctx.save();
  quadPath(q);
  ctx.clip();
  ctx.globalAlpha = presence;
  if (haveAI) {
    ctx.drawImage(sty, 0, 0, canvas.width, canvas.height);
  } else {
    ctx.filter = "hue-rotate(140deg) saturate(1.7) contrast(1.15)";
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    ctx.filter = "none";
  }
  ctx.restore();
  ctx.globalAlpha = 1;
}

function drawOutline(q, t) {
  ctx.save();
  ctx.globalAlpha = presence;
  quadPath(q);
  ctx.setLineDash([10, 8]);
  ctx.lineDashOffset = -t * 40;
  ctx.lineWidth = 2;
  ctx.strokeStyle = "rgba(255,255,255,0.95)";
  ctx.shadowColor = "rgba(0,0,0,0.5)";
  ctx.shadowBlur = 6;
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.lineDashOffset = 0;
  ctx.shadowBlur = 0;
  q.forEach((p, i) => {
    const r = 7 + Math.sin(t * 3 + i * 1.5) * 1.5;
    const halo = (t * 0.8 + i * 0.25) % 1;
    ctx.beginPath();
    ctx.arc(p.x, p.y, r + halo * 14, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(255,255,255,${0.5 * (1 - halo) * presence})`;
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.fillStyle = "#fff";
    ctx.fill();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.strokeStyle = "rgba(0,0,0,0.25)";
    ctx.lineWidth = 1.5;
    ctx.stroke();
  });
  ctx.restore();
}

let lastVideoTime = -1;
function loop() {
  if (!orig.paused && !orig.ended) requestAnimationFrame(loop);

  ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);

  if (orig.currentTime !== lastVideoTime) {
    lastVideoTime = orig.currentTime;
    // Frames that play before the tracker has loaded still count, as untracked.
    // Skipping them would measure a suffix of the clip and call it the whole.
    if (landmarker) {
      const res = landmarker.detectForVideo(orig, performance.now());
      updateTracker(res.landmarks || []);
    }
    sampledFrames++;
    // Same condition the renderer uses below, so this counts frames the window
    // was actually visible on, not frames a quad merely existed on.
    if (corners && presence > 0.01) trackedFrames++;
  }

  // Keep the stylized video in step with the original.
  if (haveAI && Math.abs(sty.currentTime - orig.currentTime) > 0.15) {
    sty.currentTime = orig.currentTime;
  }

  if (corners && presence > 0.01) {
    drawWindow(corners);
    drawOutline(corners, orig.currentTime);
  }
}

async function playThrough() {
  corners = null;
  presence = 0;
  frameActive = false;
  lostFrames = 0;
  jumpFrames = 0;
  sampledFrames = 0;
  trackedFrames = 0;
  orig.currentTime = 0;
  if (haveAI) {
    sty.currentTime = 0;
    sty.play();
  }
  await orig.play();
  requestAnimationFrame(loop);
}

// How much of the clip the finger frame was found on. composite.py already
// reports this on the CLI; without it, a clip where the gesture was never
// recognised finishes with the exact same message as a perfect run.
function trackingSummary() {
  if (!sampledFrames) return "";
  if (!landmarker) {
    return " ⚠️ The hand tracker never loaded, so nothing could be tracked.";
  }
  if (!trackedFrames) {
    return (
      " ⚠️ The finger-frame gesture was never detected. Hold both hands up with" +
      " thumb and index spread into an L, so the four fingertips outline a" +
      " rectangle."
    );
  }
  const pct = Math.round((trackedFrames / sampledFrames) * 100);
  return pct < 25
    ? ` ⚠️ Finger frame found on only ${pct}% of the clip.`
    : ` Finger frame tracked on ${pct}% of the clip.`;
}

btnPlay.addEventListener("click", () => {
  if (exporting) return;
  orig.onended = () => {
    orig.onended = null;
    // Only claim the status pill if nothing else took it over mid-preview,
    // so a generation started during the preview keeps reporting progress.
    if (statusEl.textContent !== "Previewing…") return;
    status("Preview finished." + trackingSummary());
  };
  playThrough();
  status("Previewing…");
});

// ---- export (canvas capture -> webm download) ----
btnExport.addEventListener("click", async () => {
  if (exporting) return;
  exporting = true;
  btnExport.disabled = true;
  btnPlay.disabled = true;
  status("Exporting — playing the video through once…");

  const stream = canvas.captureStream(30);
  // Prefer MP4 where the browser can record it (Safari, newer Chrome);
  // fall back to WebM elsewhere.
  const mime = [
    "video/mp4;codecs=avc1.42E01E",
    "video/mp4",
    "video/webm;codecs=vp9",
    "video/webm",
  ].find((m) => MediaRecorder.isTypeSupported(m)) || "video/webm";
  const isMp4 = mime.startsWith("video/mp4");
  recorder = new MediaRecorder(stream, {
    mimeType: mime,
    videoBitsPerSecond: 10_000_000,
  });
  const chunks = [];
  recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data);
  recorder.onstop = () => {
    const ext = isMp4 ? "mp4" : "webm";
    const blob = new Blob(chunks, { type: isMp4 ? "video/mp4" : "video/webm" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `finger-frame-ai.${ext}`;
    a.click();
    status(
      `Exported finger-frame-ai.${ext}.` +
      trackingSummary() +
      (isMp4
        ? ""
        : " (This browser records WebM — convert with: ffmpeg -i finger-frame-ai.webm -c:v libx264 out.mp4)")
    );
    exporting = false;
    btnExport.disabled = false;
    btnPlay.disabled = false;
  };

  orig.onended = () => {
    orig.onended = null;
    recorder.stop();
  };
  recorder.start();
  await playThrough();
});
